apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oixf9lrwv-go 
  janus-idp.io/tekton: oixf9lrwv-go
  backstage.io/kubernetes-id: oixf9lrwv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oixf9lrwv-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  